### ISSUE TITLE
add spacing to menu item logo popup

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#177]
would be easier to read with more vertical and horizontal spacing

**Comment by holta** [comment]
Are you talking about @floydianslips 's #159 ?

**Comment by holta** [comment]
> would be easier to read with more vertical and horizontal spacing

Unclear if the above is referring to spacing within the grid of logos, or around the outer edge of the entire pop-up, but either way:

- The white bar (on the right) appears visually awkward
- Might it possible to mouseover or hover over any particular logo, in order to see a larger version in more detail?
  - And/or show larger logos to begin with?

**Comment by floydianslips** [comment]
PR Select menu icon #191

**Comment by holta** [comment]
@floydianslips & I think the cosmetics are far improved and good to go.

Feedback welcome on #192 if others can do better?
