### ISSUE TITLE
missing icons

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#219]
en-catdogbooks_logo.png 404 (Not Found)
en-mustardseedbooks_logo.png 404 (Not Found)
en-openstax_OpenStaxLogo.jpeg 404 (Not Found)

on current master

**Comment by holta** [comment]
There is no good reason for any of us to keep manually renaming such images again and again.  Is some script (or some person?) duplicate copies of all these images out of some misguided attempt to create backup copies?  Or this there some other root cause for this completely unnecessary pattern making life difficult for everyone involved?

For whatever reason the KOC Uganda IIAB uses these images with long filenames:
en-catdogbooks_logo.png
en-mustardseedbooks_logo.png
en-openstax_OpenStaxLogo.jpeg

Which are the exact same image as contained in https://github.com/iiab/iiab-admin-console/tree/master/roles/js-menu/files/menu-files/images with short filenames here:
https://github.com/iiab/iiab-admin-console/blob/master/roles/js-menu/files/menu-files/images/en-catdogbooks.png
https://github.com/iiab/iiab-admin-console/blob/master/roles/js-menu/files/menu-files/images/en-mustardseedbooks.png
https://github.com/iiab/iiab-admin-console/blob/master/roles/js-menu/files/menu-files/images/en-openstax.jpeg

A script is apparently creating the .json outlines used by the json files below, perhaps directly from OER2Go.org metadata or such (is that script or similar in need of improvement?)
https://github.com/iiab/iiab-admin-console/blob/master/roles/js-menu/files/menu-files/menu-defs/en-catdogbooks.json
https://github.com/iiab/iiab-admin-console/blob/master/roles/js-menu/files/menu-files/menu-defs/en-mustardseedbooks.json
https://github.com/iiab/iiab-admin-console/blob/master/roles/js-menu/files/menu-files/menu-defs/en-openstax.json

**Comment by tim-moody** [comment]
Auto generated files are not assumed to be accurate, but are expected to be edited, and they are not automatically added to the repo, and they do not overwrite existing files. They can only compute the logo name, and we don't currently try to download it. So I only see one en-catdogbooks.json which means someone changed or accepted the logo and someone added it to the repo.

Files added to the repo should be edited and tested, not just the text but the logo.

Not sure what the script should do different, though it could be responsible for the extra fields. I suppose it could try to find a similarly name image and call that the logo, but this will go wrong just as often and be harder to spot. It is not possible without AI to create accurate json files, but it is either to change than to create.

**Comment by holta** [comment]
That helps explain what's happening behind the scenes, thanks:

Now where exactly we find OER2Go's original name for these images?

i.e. probably best to stick with those names to avoid most/all such hassles?

**Comment by tim-moody** [comment]
This sounds a lot easier than it is and will vary by module. First, since the catalog broke there are no logo names in it. Second, in the case of Cats and Dogs the name is logo.png, probably to make RACHEL navigation generation easier.

**Comment by holta** [comment]
What a mess.

Ok let's stick with the short names for now then.

Which at least means no renaming of images is required within https://github.com/iiab/iiab-admin-console/tree/master/roles/js-menu/files/menu-files/images

**Comment by holta** [comment]
Plz merge PR #221
