### ISSUE TITLE
Authenticate via secure user/password without basic auth

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#314]
Tracked in https://github.com/iiab/iiab-admin-console/projects/3

**Comment by holta** [comment]
Related:

PR #324 "0.4.1.4 remove auth_pam and basic auth"

**Comment by tim-moody** [comment]
#327

**Comment by floydianslips** [comment]
I have tested this a bit and there doesn't seem to be any issues with NC or Kolibri. I also like the addition of the logout button. 

The only thing I notice straight away is that you need to log back in to the admin console if you refresh the browser. Not sure if that is by design, just something I noticed.

**Comment by holta** [comment]
@floydianslips excellent feedback!

1) I noticed the same on Raspbian Lite...as you noticed on Ubuntu 20.04 LTS (both of us on Raspberry Pi 4 hardware presumably!)

2) This conversation should really be happening on PR #327 which is what's currently installed by `curl d.iiab.io/install-test.txt | sudo bash`

**Comment by tim-moody** [comment]
>The only thing I notice straight away is that you need to log back in to the admin console if you refresh the browser. Not sure if that is by design, just something I noticed.

That is an intentional part of the design in the sense that I don't want to store a password and keys outside of the browser. It is also how things worked with basic auth.
