### ISSUE TITLE
improve 'no response' message

### ISSUE THREAD

**Issue by tim-moody** [iiab/iiab-admin-console#362]
cmdsrv uwsgi wrapper reports health of cmdsrv in three ways:

- if iiab-cmdsrv.pid is absent then cmdsrv is not running: CMDSRV is not running.
- if iiab-cmdsrv-ready is absent then cmdsrv has started but not yet reached the thread monitor state: CMDSRV has started but is not ready.
- if the request times out (currently 30000 ms): No Response from CMDSRV in 30000 ms

The last response was more generic because it could mean crashed or not running, but in reality it is almost always a timeout due to business of the server, so the message could reflect this.

**Comment by holta** [comment]
My result on RPi 4 with 4GB [*] is that 2-or-more simultaneous downloads of RACHEL/OER2Go Modules blocks the ability to visit/view Admin Console > Utilities > Display Job Status every time.

One single downlaod of a RACHEL/OER2GO Module does not result in this problem.

[*] 64-bit RaspiOS Lite

**Comment by tim-moody** [comment]
please try the timeout experiment I mentioned
please confirm that there are no python erros

**Comment by tim-moody** [comment]
>My result on RPi 4 with 4GB [*] is that 2-or-more simultaneous downloads of RACHEL/OER2Go Modules ...ends up blocking the ability to visit/view Admin Console > Utilities > Display Job Status every single time (so far anyway!)

how many attempts?

**Comment by holta** [comment]
> > My result on RPi 4 with 4GB [*] is that 2-or-more simultaneous downloads of RACHEL/OER2Go Modules ...ends up blocking the ability to visit/view Admin Console > Utilities > Display Job Status every single time (so far anyway!)
> 
> how many attempts?

More than 10 attempts to visit the Utilities > Display Job Status page.  Every attempt failed when there was more than 1 RACHEL/OER2Go modules being downloaded.  A dozen were added at first.  And then a couple more, causing the same failure.

> which oer2go modules?

    "en-blockly-games",
    "en-feed-the-monster",
    "en-math_expression",
    "en-catdogbooks",
    "en-musictheory",
    "en-mustardseedbooks",
    "en-ebooks",
    "en-algebra2go",
    "en-storybooks",
    "en-ck12",
    "en-radiolab",
    "en-understanding_algebra",
    "en-infonet",
    "en-practical_action",

**Comment by holta** [comment]
> please confirm that there are no python errors

After 1 full minute, the output remains...

```
root@box:/opt/admin/cmdsrv# ./iiab-cmdsrv3.py
in job_minder_thread
```

So I assume that means no Python errors.

**Comment by tim-moody** [comment]
>So I assume that means no Python errors.

when idle. says nothing about when downloading oer2go or anything else

**Comment by tim-moody** [comment]
>As these completed

To be clear, all modules downloaded successfully and after completed done job-status reported the fact correctly?

**Comment by holta** [comment]
> To be clear, all modules downloaded successfully and after completed done job-status reported the fact correctly?

Yes

**Comment by tim-moody** [comment]
on rpi 4 I downloaded about 9 modules and never saw more than 3 second response on job stat.

on rpi w I downloaded 3 more and job stat response was 2 - 3 seconds, with kolibri running

**Comment by shanti-bhardwa** [comment]
testing medical build of iiab 7.2 on rasbpian 32 bit desktop. Can't get Admin Console to work:
Init fails.
Did restart of iiab-cmdsrv as well but iiab-cmdsrv fails each time I login in
iiab-cmdsrv.service - Provides the IIAB Command Server
   Loaded: loaded (/etc/systemd/system/iiab-cmdsrv.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2020-11-09 13:35:30 GMT; 24min ago
  Process: 651 ExecStart=/opt/admin/cmdsrv/iiab-cmdsrv3.py --daemon (code=exited, status=0/SUCCESS)
 Main PID: 1505 (iiab-cmdsrv3.py)
    Tasks: 9 (limit: 4915)
   CGroup: /system.slice/iiab-cmdsrv.service
           └─1505 /usr/bin/python3 /opt/admin/cmdsrv/iiab-cmdsrv3.py --daemon

Nov 09 13:59:00 box.lan IIAB-CMDSRV[1505]: IIAB-CMDSRV : Received CMD Message GET-ADM-CONF.
Nov 09 13:59:03 box.lan IIAB-CMDSRV[1505]: IIAB-CMDSRV : Received CMD Message GET-VARS.
Nov 09 13:59:03 box.lan IIAB-CMDSRV[1505]: IIAB-CMDSRV : Received CMD Message GET-ANS.
Nov 09 13:59:03 box.lan IIAB-CMDSRV[1505]: IIAB-CMDSRV : Received CMD Message GET-IIAB-INI.
Nov 09 13:59:03 box.lan IIAB-CMDSRV[1505]: IIAB-CMDSRV : Received CMD Message GET-ZIM-STAT.
Nov 09 13:59:18 box.lan IIAB-CMDSRV[1505]: IIAB-CMDSRV : Received CMD Message GET-OER2GO-STAT.
Nov 09 13:59:29 box.lan IIAB-CMDSRV[1505]: IIAB-CMDSRV : Received CMD Message GET-OSM-VECT-STAT.
Nov 09 13:59:35 box.lan IIAB-CMDSRV[1505]: IIAB-CMDSRV : Received CMD Message GET-SPACE-AVAIL.
Nov 09 13:59:35 box.lan IIAB-CMDSRV[1505]: IIAB-CMDSRV : Received CMD Message GET-EXTDEV-INFO.
Nov 09 13:59:50 box.lan IIAB-CMDSRV[1505]: IIAB-CMDSRV : Error: Unexpected error in Command GET-OSM-VECT-STAT.


11/9/2020, 2:03:38 PM: GET-ZIM-STAT SUCCEEDED (341 ms)
11/9/2020, 2:03:38 PM: GET-IIAB-INI SUCCEEDED (299 ms)
11/9/2020, 2:03:38 PM: GET-ANS SUCCEEDED (236 ms)
11/9/2020, 2:03:38 PM: GET-VARS SUCCEEDED (85 ms)


Starting Application
11/9/2020, 2:14:22 PM: GET-SPACE-AVAIL SUCCEEDED (5470 ms)
11/9/2020, 2:14:22 PM: GET-OSM-VECT-STAT FAILED and returned Unexpected error i$
11/9/2020, 2:14:22 PM: GET-OER2GO-STAT SUCCEEDED (14348 ms)
11/9/2020, 2:14:22 PM: GET-ZIM-STAT SUCCEEDED (14191 ms)
11/9/2020, 2:14:17 PM: GET-IIAB-INI SUCCEEDED (9490 ms)
11/9/2020, 2:14:15 PM: GET-ANS SUCCEEDED (15166 ms)
11/9/2020, 2:14:08 PM: Init Failed
11/9/2020, 2:14:07 PM: GET-VARS SUCCEEDED (7187 ms)
11/9/2020, 2:14:03 PM: Command GET-EXTDEV-INFO sent to server
11/9/2020, 2:14:03 PM: Command GET-SPACE-AVAIL sent to server
11/9/2020, 2:14:03 PM: Command GET-OSM-VECT-STAT sent to server
11/9/2020, 2:14:03 PM: Command GET-OER2GO-STAT sent to server

**Comment by shanti-bhardwa** [comment]
tried running iiab-cmdsrv3.py , get systax error on line 239. 
Also /opt/admin/cmdsrv access is for root only

**Comment by shanti-bhardwa** [comment]
see http://spruge.us/T1lDrq

**Comment by shanti-bhardwa** [comment]
https://sprunge.us/T1lDrq

**Comment by tim-moody** [comment]
>Nov 09 13:59:50 box.lan IIAB-CMDSRV[1505]: IIAB-CMDSRV : Error: Unexpected error in Command GET-OSM-VECT-STAT.

what is the state of the maps install?

**Comment by tim-moody** [comment]
on my test vm

11/9/2020, 4:10:08 PM: GET-OSM-VECT-STAT SUCCEEDED (15 ms)

**Comment by tim-moody** [comment]
Actually you said medical version, which does not install osm, but I am testing on vm with osm. I wonder if the test for osm installed gets confused by your usb boot.

**Comment by tim-moody** [comment]
I have reproduced the problem.

**Comment by tim-moody** [comment]
#367 should fix it.

**Comment by tim-moody** [comment]
Please note that the osm error has nothing to do with this ticket.

**Comment by tim-moody** [comment]
work pertaining to the title of this ticket is complete
