### ISSUE TITLE
Duplicate ZIMs very hard to visualize in "Remove Content"

### ISSUE THREAD

**Issue by holta** [iiab/iiab-admin-console#71]
1) Is it possible the ZIM deletion interface[*] could sort all installed ZIMs alphabetically by filename (or by name) to make deletion of outdated-but-similarly-named ZIM files much easier?

2) Or perhaps better: could the UX match the order shown on the "Get ZIM Files from Kiwix" page?

3) In the distant future, would it make sense to add & delete ZIMs from the very same page, instead of having 2 separate pages?

[*] http://box/admin -> Install Content -> Remove Content

**Comment by tim-moody** [comment]
I considered both of these ideas. I should have sorted the names as in 2., but because of expediency and the expectation of a relatively short list I didn't. Still could at some point.

I rejected 3. because Install Zims is already cluttered and also because I think it is useful to see both zims and oer2go when deleting.

**Comment by tim-moody** [comment]
2, implemented in #72
